name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  workflow_dispatch:
jobs:
  build_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - name: Build page
        run: yarn build
